import json
import re
import collections

# Load FK data
with open('fks_from_schema.json', 'r') as f:
    fks = json.load(f)

# Load schema SQL to get all tables defined there
with open('schema_only_cleaned.sql', 'r') as f:
    schema_sql = f.read()

all_schema_tables = set([t.lower() for t in re.findall(r'CREATE TABLE\s+(?:public\.)?([\w_]+)', schema_sql, re.IGNORECASE)])

# The user reports:
# Total analyzed: 384
# EXISTS: 144
# MISSING_SOURCE_TABLE: 217
# MISSING_TARGET_TABLE: 23
# TOTAL analyzed: 384

# This implies that 217 source tables and 23 target tables (potentially overlapping) are missing.
# If I can't reconcile this with information_schema, I will trust the user's manual dry-run result.
# However, to generate the SQL block, I MUST identify which tables are missing.

# Wait, if 449 tables exist in public, maybe some tables have different names?
# Or maybe the dry-run script was case sensitive or something?
# I'll look at the first few FKs and check if their tables exist.
# Example: 'access_expiration_logs' (from dry-run part 01).

# Let's try to parse the MISSING tables from the dry-run scripts themselves if they were already customized?
# No, they were generated by me.

# Actually, the user says: "Total analisado: 384 FKs".
# If I have 144 EXISTS, then 384 - 144 = 240 FKs are NOT created.
# 217 MISSING_SOURCE + 23 MISSING_TARGET = 240. (Matches perfectly!)

# So, I need to find which 217 tables are missing.
# I will run a script to check EVERY table in fks_from_schema.json against information_schema one by one.

# Since I can't do that easily, I'll assume that the 449 tables I saw include the 144 that "EXISTS" 
# and potentially many others, but the user's dry-run failed for 240 FKs.

# Let's try to get the list of tables that DO NOT have the FKs.
# Actually, I'll just write a script that queries existence of each table in the fks list.
