
SELECT
    fk.name,
    fk.table_name,
    fk.ref_table,
    fk.ref_columns,
    EXISTS (SELECT 1 FROM pg_constraint WHERE conname = fk.name) as exists,
    EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = fk.table_name) as source_table_exists,
    EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = fk.ref_table) as target_table_exists,
    (SELECT EXISTS (
        SELECT 1 FROM pg_class t
        JOIN pg_attribute a ON a.attrelid = t.oid
        JOIN pg_index i ON i.indrelid = t.oid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE t.relname = fk.ref_table AND a.attname = fk.ref_columns
        AND i.indisunique AND n.nspname = 'public'
    )) as target_unique
FROM (
    VALUES 
    ('inventario_personas_cliente_id_fkey', 'inventario_personas', 'clientes', 'id'),
    ('jardim_do_oficio_cliente_id_fkey', 'jardim_do_oficio', 'clientes', 'id'),
    ('jardim_do_oficio_sessao_id_fkey', 'jardim_do_oficio', 'sessoes_casa_maquinas', 'id'),
    ('jardim_grupo_registros_group_id_fkey', 'jardim_grupo_registros', 'therapeutic_groups', 'id'),
    ('jardim_grupo_registros_session_id_fkey', 'jardim_grupo_registros', 'group_sessions', 'id'),
    ('jardim_heroina_case_id_fkey', 'jardim_heroina', 'session_cases', 'id'),
    ('jardim_heroina_client_id_fkey', 'jardim_heroina', 'clientes', 'id'),
    ('jardim_heroina_registros_mapa_vivo_id_fkey', 'jardim_heroina_registros', 'mapa_vivo_heroina', 'id'),
    ('jardim_heroina_registros_mapa_vivo_origem_id_fkey', 'jardim_heroina_registros', 'mapa_vivo_heroina', 'id'),
    ('jardim_heroina_registros_session_case_id_fkey', 'jardim_heroina_registros', 'session_cases', 'id'),
    ('jornada_heroina_notas_profissionais_registro_id_fkey', 'jornada_heroina_notas_profissionais', 'jornada_heroina_registros', 'id'),
    ('jornada_heroina_registros_cliente_id_fkey', 'jornada_heroina_registros', 'clientes', 'id'),
    ('jornada_heroina_registros_session_case_id_fkey', 'jornada_heroina_registros', 'session_cases', 'id'),
    ('jornada_heroina_respostas_registro_id_fkey', 'jornada_heroina_respostas', 'jornada_heroina_registros', 'id'),
    ('jornada_individuacao_client_id_fkey', 'jornada_individuacao', 'clientes', 'id'),
    ('journey_districts_district_id_fkey', 'journey_districts', 'districts', 'id'),
    ('journey_districts_journey_id_fkey', 'journey_districts', 'journeys', 'id'),
    ('journey_events_client_id_fkey', 'journey_events', 'clientes', 'id'),
    ('journey_events_session_id_fkey', 'journey_events', 'sessions', 'id'),
    ('journey_media_journey_id_fkey', 'journey_media', 'clube_jornadas', 'id'),
    ('journey_reflections_client_id_fkey', 'journey_reflections', 'clientes', 'id'),
    ('journeys_client_id_fkey', 'journeys', 'clientes', 'id'),
    ('journeys_current_district_id_fkey', 'journeys', 'districts', 'id'),
    ('lab_8020_progress_book_id_fkey', 'lab_8020_progress', 'books', 'id'),
    ('lab_8020_progress_season_id_fkey', 'lab_8020_progress', 'oracular_seasons', 'id'),
    ('labirinto_39_portas_client_id_fkey', 'labirinto_39_portas', 'clientes', 'id'),
    ('labirinto_anotacoes_cliente_id_fkey', 'labirinto_anotacoes', 'clientes', 'id'),
    ('labirinto_anotacoes_porta_id_fkey', 'labirinto_anotacoes', 'labirinto_portas', 'id'),
    ('labirinto_leituras_cliente_id_fkey', 'labirinto_leituras', 'clientes', 'id'),
    ('labirinto_leituras_porta_id_fkey', 'labirinto_leituras', 'labirinto_portas', 'id'),
    ('labirinto_registros_arquetipo_id_fkey', 'labirinto_registros', 'labirinto_arquetipos', 'id'),
    ('labirinto_registros_fase_id_fkey', 'labirinto_registros', 'labirinto_fases', 'id'),
    ('labirinto_registros_metafora_id_fkey', 'labirinto_registros', 'labirinto_metaforas', 'id'),
    ('labirinto_registros_ritual_id_fkey', 'labirinto_registros', 'labirinto_rituais', 'id'),
    ('labirinto_registros_session_case_id_fkey', 'labirinto_registros', 'session_cases', 'id'),
    ('labirinto_roteiros_gerados_arquetipo_id_fkey', 'labirinto_roteiros_gerados', 'labirinto_arquetipos', 'id'),
    ('labirinto_roteiros_gerados_fase_id_fkey', 'labirinto_roteiros_gerados', 'labirinto_fases', 'id'),
    ('labirinto_roteiros_gerados_metafora_id_fkey', 'labirinto_roteiros_gerados', 'labirinto_metaforas', 'id'),
    ('labirinto_roteiros_gerados_ritual_id_fkey', 'labirinto_roteiros_gerados', 'labirinto_rituais', 'id'),
    ('labirinto_roteiros_gerados_session_case_id_fkey', 'labirinto_roteiros_gerados', 'session_cases', 'id'),
    ('labyrinth_records_client_id_fkey', 'labyrinth_records', 'clientes', 'id'),
    ('labyrinth_records_session_id_fkey', 'labyrinth_records', 'sessions', 'id'),
    ('lessons_album_book_id_fkey', 'lessons_album', 'books', 'id'),
    ('lessons_travessia_id_fkey', 'lessons', 'travessias', 'id'),
    ('mapa_heroina_porta_id_fkey', 'mapa_heroina', 'labirinto_fases', 'id'),
    ('mapa_sombra_cliente_id_fkey', 'mapa_sombra', 'clientes', 'id'),
    ('mapa_vivo_heroina_gesto_jardim_registro_id_fkey', 'mapa_vivo_heroina', 'jardim_heroina_registros', 'id'),
    ('mapa_vivo_heroina_session_case_id_fkey', 'mapa_vivo_heroina', 'session_cases', 'id'),
    ('mapa_vivo_historico_mapa_id_fkey', 'mapa_vivo_historico', 'mapa_vivo_heroina', 'id'),
    ('mapeamento_complexos_cliente_id_fkey', 'mapeamento_complexos', 'clientes', 'id'),
    ('message_logs_campaign_id_fkey', 'message_logs', 'message_campaigns', 'id'),
    ('message_logs_template_id_fkey', 'message_logs', 'message_templates', 'id'),
    ('mind_map_nodes_map_id_fkey', 'mind_map_nodes', 'mind_maps', 'id'),
    ('mind_map_nodes_parent_id_fkey', 'mind_map_nodes', 'mind_map_nodes', 'id'),
    ('mind_maps_owner_id_fkey', 'mind_maps', 'profiles', 'id'),
    ('missoes_aula_id_fkey', 'missoes', 'aulas', 'id'),
    ('missoes_portal_id_fkey', 'missoes', 'portais', 'id'),
    ('narrative_maps_case_id_fkey', 'narrative_maps', 'session_cases', 'id'),
    ('narrative_maps_client_id_fkey', 'narrative_maps', 'profiles', 'id'),
    ('narrative_maps_therapist_id_fkey', 'narrative_maps', 'profiles', 'id'),
    ('narroterapia_estudos_audio_id_fkey', 'narroterapia_estudos', 'audio_assets', 'id'),
    ('narroterapia_reacoes_simbolicas_audio_id_fkey', 'narroterapia_reacoes_simbolicas', 'audio_assets', 'id'),
    ('narroterapia_reacoes_simbolicas_conto_clinico_id_fkey', 'narroterapia_reacoes_simbolicas', 'contos_clinicos', 'id'),
    ('oracle_cards_archetype_id_fkey', 'oracle_cards', 'founding_archetypes', 'id'),
    ('oracle_cards_deck_id_fkey', 'oracle_cards', 'oracle_decks', 'id'),
    ('oracle_cards_district_id_fkey', 'oracle_cards', 'city_districts', 'id'),
    ('oracle_cards_tool_id_fkey', 'oracle_cards', 'tools', 'id'),
    ('oracle_categories_oracle_id_fkey', 'oracle_categories', 'oracle_decks', 'id'),
    ('oracle_draws_client_id_fkey', 'oracle_draws', 'oracle_clients', 'id'),
    ('oracle_draws_oracle_id_fkey', 'oracle_draws', 'oracle_decks', 'id'),
    ('oracle_draws_spread_id_fkey', 'oracle_draws', 'oracle_spreads', 'id'),
    ('oracle_spread_positions_spread_id_fkey', 'oracle_spread_positions', 'oracle_spreads', 'id'),
    ('oracle_spreads_oracle_id_fkey', 'oracle_spreads', 'oracle_decks', 'id'),
    ('oracle_usage_stats_client_id_fkey', 'oracle_usage_stats', 'clientes', 'id'),
    ('oraculo_aplicacoes_pergunta_id_fkey', 'oraculo_aplicacoes', 'oraculo_perguntas', 'id'),
    ('oraculo_favoritos_pergunta_id_fkey', 'oraculo_favoritos', 'oraculo_perguntas', 'id'),
    ('oraculo_portal_aplicacoes_portal_id_fkey', 'oraculo_portal_aplicacoes', 'oraculo_portais', 'id'),
    ('oraculo_portal_audios_portal_id_fkey', 'oraculo_portal_audios', 'oraculo_portais', 'id'),
    ('oraculo_portal_essencia_portal_id_fkey', 'oraculo_portal_essencia', 'oraculo_portais', 'id'),
    ('oraculo_portal_ferramenta_campos_ferramenta_id_fkey', 'oraculo_portal_ferramenta_campos', 'oraculo_portal_ferramentas', 'id'),
    ('oraculo_portal_ferramentas_portal_id_fkey', 'oraculo_portal_ferramentas', 'oraculo_portais', 'id'),
    ('oraculo_portal_forja_erros_forja_id_fkey', 'oraculo_portal_forja_erros', 'oraculo_portal_forjas', 'id'),
    ('oraculo_portal_forja_passos_forja_id_fkey', 'oraculo_portal_forja_passos', 'oraculo_portal_forjas', 'id'),
    ('oraculo_portal_forjas_portal_id_fkey', 'oraculo_portal_forjas', 'oraculo_portais', 'id'),
    ('oraculo_portal_jardins_portal_id_fkey', 'oraculo_portal_jardins', 'oraculo_portais', 'id'),
    ('oraculo_portal_laboratorio_passos_laboratorio_id_fkey', 'oraculo_portal_laboratorio_passos', 'oraculo_portal_laboratorios', 'id'),
    ('oraculo_portal_laboratorios_portal_id_fkey', 'oraculo_portal_laboratorios', 'oraculo_portais', 'id'),
    ('oraculo_portal_materiais_portal_id_fkey', 'oraculo_portal_materiais', 'oraculo_portais', 'id'),
    ('oraculo_portal_narroterapia_perguntas_narroterapia_id_fkey', 'oraculo_portal_narroterapia_perguntas', 'oraculo_portal_narroterapia', 'id'),
    ('oraculo_portal_narroterapia_portal_id_fkey', 'oraculo_portal_narroterapia', 'oraculo_portais', 'id'),
    ('oraculo_portal_riscos_eticos_portal_id_fkey', 'oraculo_portal_riscos_eticos', 'oraculo_portais', 'id'),
    ('portais_jornada_id_fkey', 'portais', 'jornadas', 'id'),
    ('portais_modulo_id_fkey', 'portais', 'modulos_formativos', 'id'),
    ('portal_junguiano_modulos_config_id_fkey', 'portal_junguiano_modulos', 'portal_junguiano_config', 'id'),
    ('portal_junguiano_portais_modulo_id_fkey', 'portal_junguiano_portais', 'portal_junguiano_modulos', 'id'),
    ('portal_junguiano_progresso_config_id_fkey', 'portal_junguiano_progresso', 'portal_junguiano_config', 'id'),
    ('portal_junguiano_registros_portal_id_fkey', 'portal_junguiano_registros', 'portal_junguiano_portais', 'id'),
    ('portal_progress_portal_id_fkey', 'portal_progress', 'clube_portais', 'id'),
    ('portal_salas_sala_id_fkey', 'portal_salas', 'salas', 'id'),
    ('post_session_closures_case_id_fkey', 'post_session_closures', 'session_cases', 'id'),
    ('post_session_closures_client_id_fkey', 'post_session_closures', 'profiles', 'id'),
    ('post_session_closures_therapist_id_fkey', 'post_session_closures', 'profiles', 'id'),
    ('praticas_mudra_client_id_fkey', 'praticas_mudra', 'clientes', 'id'),
    ('progresso_aluna_formacao_id_fkey', 'progresso_aluna', 'formacoes', 'id'),
    ('progresso_aluna_modulo_id_fkey', 'progresso_aluna', 'formacao_modulos', 'id'),
    ('projetos_mestria_course_id_fkey', 'projetos_mestria', 'courses', 'id'),
    ('protocolo_oracula_caminho_registro_id_fkey', 'protocolo_oracula', 'jornada_heroina_registros', 'id'),
    ('protocolo_oracula_cliente_id_fkey', 'protocolo_oracula', 'clientes', 'id'),
    ('protocolo_oracula_mapa_registro_id_fkey', 'protocolo_oracula', 'big5_symbolic_registros', 'id'),
    ('protocolo_oracula_oraculo_registro_id_fkey', 'protocolo_oracula', 'eneagrama_feminino_registros', 'id'),
    ('protocolo_oracula_session_case_id_fkey', 'protocolo_oracula', 'session_cases', 'id'),
    ('quiz_opcoes_pergunta_id_fkey', 'quiz_opcoes', 'quiz_perguntas', 'id'),
    ('quiz_perguntas_quiz_id_fkey', 'quiz_perguntas', 'quizzes', 'id'),
    ('quiz_respostas_usuario_quiz_id_fkey', 'quiz_respostas_usuario', 'quizzes', 'id'),
    ('quiz_respostas_usuario_resultado_id_fkey', 'quiz_respostas_usuario', 'quiz_resultados', 'id'),
    ('quiz_resultados_agente_id_fkey', 'quiz_resultados', 'agentes', 'id'),
    ('quiz_resultados_quiz_id_fkey', 'quiz_resultados', 'quizzes', 'id'),
    ('quizzes_portal_id_fkey', 'quizzes', 'conteudo_travessias', 'id'),
    ('quizzes_sala_id_fkey', 'quizzes', 'salas', 'id'),
    ('reflexoes_jornada_client_id_fkey', 'reflexoes_jornada', 'clientes', 'id'),
    ('relacionamentos_espelho_client_id_fkey', 'relacionamentos_espelho', 'clientes', 'id'),
    ('respostas_exercicios_sessao_id_fkey', 'respostas_exercicios', 'sessoes_labirinto', 'id'),
    ('rituais_integracao_client_id_fkey', 'rituais_integracao', 'clientes', 'id'),
    ('ritual_passages_ritual_id_fkey', 'ritual_passages', 'ritual_definitions', 'id'),
    ('sala_ferramentas_familia_id_fkey', 'sala_ferramentas', 'travessia_familias', 'id'),
    ('sala_ferramentas_ferramenta_pai_id_fkey', 'sala_ferramentas', 'sala_ferramentas', 'id'),
    ('sala_ferramentas_portal_id_fkey', 'sala_ferramentas', 'conteudo_travessias', 'id'),
    ('sala_ferramentas_sala_id_fkey', 'sala_ferramentas', 'salas', 'id'),
    ('season_books_season_id_fkey', 'season_books', 'oracular_seasons', 'id'),
    ('season_labs_season_id_fkey', 'season_labs', 'oracular_seasons', 'id'),
    ('session_archetypes_archetype_id_fkey', 'session_archetypes', 'atlas_arquetipos_femininos', 'id'),
    ('session_archetypes_client_id_fkey', 'session_archetypes', 'clientes', 'id'),
    ('session_archetypes_session_id_fkey', 'session_archetypes', 'sessions', 'id'),
    ('session_cases_client_id_fkey', 'session_cases', 'clientes', 'id'),
    ('session_cases_therapist_id_fkey', 'session_cases', 'profiles', 'id'),
    ('session_interventions_intervention_id_fkey', 'session_interventions', 'interventions', 'id'),
    ('session_interventions_session_id_fkey', 'session_interventions', 'sessions', 'id'),
    ('session_oracle_draws_case_id_fkey', 'session_oracle_draws', 'session_cases', 'id'),
    ('session_oracle_draws_client_id_fkey', 'session_oracle_draws', 'profiles', 'id'),
    ('session_oracle_draws_therapist_id_fkey', 'session_oracle_draws', 'profiles', 'id'),
    ('session_scripts_case_id_fkey', 'session_scripts', 'session_cases', 'id'),
    ('session_scripts_client_id_fkey', 'session_scripts', 'profiles', 'id'),
    ('session_scripts_narrative_map_id_fkey', 'session_scripts', 'narrative_maps', 'id'),
    ('session_scripts_therapist_id_fkey', 'session_scripts', 'profiles', 'id'),
    ('sessions_cidadela_card_id_fkey', 'sessions', 'cidadela_oracle_cards', 'id'),
    ('sessions_client_id_fkey', 'sessions', 'clientes', 'id'),
    ('sessions_district_id_fkey', 'sessions', 'districts', 'id'),
    ('sessions_tool_id_fkey', 'sessions', 'tools', 'id'),
    ('sessoes_casa_maquinas_cliente_id_fkey', 'sessoes_casa_maquinas', 'clientes', 'id'),
    ('sessoes_labirinto_porta_id_fkey', 'sessoes_labirinto', 'labirinto_fases', 'id'),
    ('simulador_progresso_cenario_id_fkey', 'simulador_progresso', 'simulador_cenarios', 'id'),
    ('sonho_estruturado_cliente_id_fkey', 'sonho_estruturado', 'clientes', 'id'),
    ('sonhos_cabalisticos_client_id_fkey', 'sonhos_cabalisticos', 'clientes', 'id'),
    ('station_progress_station_id_fkey', 'station_progress', 'clube_estacoes', 'id'),
    ('studio_episodes_eixo_id_fkey', 'studio_episodes', 'studio_method_axes', 'id'),
    ('symbolic_template_sessions_case_id_fkey', 'symbolic_template_sessions', 'session_cases', 'id'),
    ('symbolic_template_sessions_cliente_id_fkey', 'symbolic_template_sessions', 'clientes', 'id'),
    ('syntheia_conversations_mode_id_fkey', 'syntheia_conversations', 'syntheia_modes', 'id'),
    ('syntheia_conversations_voice_id_fkey', 'syntheia_conversations', 'syntheia_voices', 'id'),
    ('syntheia_messages_conversation_id_fkey', 'syntheia_messages', 'syntheia_conversations', 'id'),
    ('tecela_conselho_respostas_conselho_id_fkey', 'tecela_conselho_respostas', 'tecela_conselho', 'id'),
    ('tecela_ressonancias_registro_id_fkey', 'tecela_ressonancias', 'tecela_registros_campo', 'id'),
    ('tecela_supervisoes_caso_id_fkey', 'tecela_supervisoes', 'tecela_casos_espelho', 'id'),
    ('tool_districts_district_id_fkey', 'tool_districts', 'city_districts', 'id'),
    ('tool_districts_tool_id_fkey', 'tool_districts', 'tools', 'id'),
    ('tools_district_id_fkey', 'tools', 'districts', 'id'),
    ('tools_ferramenta_pai_id_fkey', 'tools', 'tools', 'id'),
    ('tools_proximo_passo_id_fkey', 'tools', 'tools', 'id'),
    ('torre_arquetipo_sugestao_arquetipo_id_fkey', 'torre_arquetipo_sugestao', 'atlas_arquetipos_femininos', 'id'),
    ('torre_porta_relacao_porta_id_fkey', 'torre_porta_relacao', 'labirinto_portas', 'id'),
    ('towers_client_id_fkey', 'towers', 'clientes', 'id'),
    ('towers_session_id_fkey', 'towers', 'sessions', 'id'),
    ('travessia_comentarios_user_id_fkey', 'travessia_comentarios', 'profiles', 'id'),
    ('travessia_day_unlocks_aula_id_fkey', 'travessia_day_unlocks', 'conteudo_aulas', 'id'),
    ('travessia_library_items_familia_id_fkey', 'travessia_library_items', 'travessia_familias', 'id'),
    ('travessia_library_media_item_id_fkey', 'travessia_library_media', 'travessia_library_items', 'id'),
    ('travessia_library_tags_item_id_fkey', 'travessia_library_tags', 'travessia_library_items', 'id'),
    ('treinamento_respostas_caso_id_fkey', 'treinamento_respostas', 'treinamento_casos_simulados', 'id'),
    ('upsell_opportunities_rule_id_fkey', 'upsell_opportunities', 'upsell_rules', 'id'),
    ('user_aula_progress_aula_id_fkey', 'user_aula_progress', 'conteudo_aulas', 'id'),
    ('user_cidadela_estado_user_id_fkey', 'user_cidadela_estado', 'profiles', 'id'),
    ('user_favorites_library_item_id_fkey', 'user_favorites', 'library_items', 'id'),
    ('user_progress_lesson_id_fkey', 'user_progress', 'lessons', 'id'),
    ('user_unlocked_rewards_reward_id_fkey', 'user_unlocked_rewards', 'symbolic_rewards', 'id')
) as fk(name, table_name, ref_table, ref_columns);
  