
WITH fks(name, src_t, src_c, tgt_t, tgt_c) AS (
    VALUES 
('group_sessions_group_id_fkey', 'group_sessions', 'group_id', 'therapeutic_groups', 'id'),
('heroina_arquetipo_registros_arquetipo_id_fkey', 'heroina_arquetipo_registros', 'arquetipo_id', 'labirinto_arquetipos', 'id'),
('heroina_cenario_registros_metafora_id_fkey', 'heroina_cenario_registros', 'metafora_id', 'labirinto_metaforas', 'id'),
('heroina_fase_ativa_fase_id_fkey', 'heroina_fase_ativa', 'fase_id', 'labirinto_fases', 'id'),
('heroina_ritual_registros_ritual_id_fkey', 'heroina_ritual_registros', 'ritual_id', 'labirinto_rituais', 'id'),
('imaginacao_ativa_cliente_id_fkey', 'imaginacao_ativa', 'cliente_id', 'clientes', 'id'),
('intervention_favorites_intervention_id_fkey', 'intervention_favorites', 'intervention_id', 'interventions', 'id'),
('interventions_district_id_fkey', 'interventions', 'district_id', 'districts', 'id'),
('inventario_personas_cliente_id_fkey', 'inventario_personas', 'cliente_id', 'clientes', 'id'),
('jardim_do_oficio_cliente_id_fkey', 'jardim_do_oficio', 'cliente_id', 'clientes', 'id'),
('jardim_do_oficio_sessao_id_fkey', 'jardim_do_oficio', 'sessao_id', 'sessoes_casa_maquinas', 'id'),
('jardim_grupo_registros_group_id_fkey', 'jardim_grupo_registros', 'group_id', 'therapeutic_groups', 'id'),
('jardim_grupo_registros_session_id_fkey', 'jardim_grupo_registros', 'session_id', 'group_sessions', 'id'),
('jardim_heroina_case_id_fkey', 'jardim_heroina', 'case_id', 'session_cases', 'id'),
('jardim_heroina_client_id_fkey', 'jardim_heroina', 'client_id', 'clientes', 'id'),
('jardim_heroina_registros_mapa_vivo_id_fkey', 'jardim_heroina_registros', 'mapa_vivo_id', 'mapa_vivo_heroina', 'id'),
('jardim_heroina_registros_mapa_vivo_origem_id_fkey', 'jardim_heroina_registros', 'mapa_vivo_origem_id', 'mapa_vivo_heroina', 'id'),
('jardim_heroina_registros_session_case_id_fkey', 'jardim_heroina_registros', 'session_case_id', 'session_cases', 'id'),
('jornada_heroina_notas_profissionais_registro_id_fkey', 'jornada_heroina_notas_profissionais', 'registro_id', 'jornada_heroina_registros', 'id'),
('jornada_heroina_registros_cliente_id_fkey', 'jornada_heroina_registros', 'cliente_id', 'clientes', 'id'),
('jornada_heroina_registros_session_case_id_fkey', 'jornada_heroina_registros', 'session_case_id', 'session_cases', 'id'),
('jornada_heroina_respostas_registro_id_fkey', 'jornada_heroina_respostas', 'registro_id', 'jornada_heroina_registros', 'id'),
('jornada_individuacao_client_id_fkey', 'jornada_individuacao', 'client_id', 'clientes', 'id'),
('journey_districts_district_id_fkey', 'journey_districts', 'district_id', 'districts', 'id'),
('journey_districts_journey_id_fkey', 'journey_districts', 'journey_id', 'journeys', 'id'),
('journey_events_client_id_fkey', 'journey_events', 'client_id', 'clientes', 'id'),
('journey_events_session_id_fkey', 'journey_events', 'session_id', 'sessions', 'id'),
('journey_media_journey_id_fkey', 'journey_media', 'journey_id', 'clube_jornadas', 'id'),
('journey_reflections_client_id_fkey', 'journey_reflections', 'client_id', 'clientes', 'id'),
('journeys_client_id_fkey', 'journeys', 'client_id', 'clientes', 'id'),
('journeys_current_district_id_fkey', 'journeys', 'current_district_id', 'districts', 'id'),
('lab_8020_progress_book_id_fkey', 'lab_8020_progress', 'book_id', 'books', 'id'),
('lab_8020_progress_season_id_fkey', 'lab_8020_progress', 'season_id', 'oracular_seasons', 'id'),
('labirinto_39_portas_client_id_fkey', 'labirinto_39_portas', 'client_id', 'clientes', 'id'),
('labirinto_anotacoes_cliente_id_fkey', 'labirinto_anotacoes', 'cliente_id', 'clientes', 'id'),
('labirinto_anotacoes_porta_id_fkey', 'labirinto_anotacoes', 'porta_id', 'labirinto_portas', 'id'),
('labirinto_leituras_cliente_id_fkey', 'labirinto_leituras', 'cliente_id', 'clientes', 'id'),
('labirinto_leituras_porta_id_fkey', 'labirinto_leituras', 'porta_id', 'labirinto_portas', 'id'),
('labirinto_registros_arquetipo_id_fkey', 'labirinto_registros', 'arquetipo_id', 'labirinto_arquetipos', 'id'),
('labirinto_registros_fase_id_fkey', 'labirinto_registros', 'fase_id', 'labirinto_fases', 'id'),
('labirinto_registros_metafora_id_fkey', 'labirinto_registros', 'metafora_id', 'labirinto_metaforas', 'id'),
('labirinto_registros_ritual_id_fkey', 'labirinto_registros', 'ritual_id', 'labirinto_rituais', 'id'),
('labirinto_registros_session_case_id_fkey', 'labirinto_registros', 'session_case_id', 'session_cases', 'id'),
('labirinto_roteiros_gerados_arquetipo_id_fkey', 'labirinto_roteiros_gerados', 'arquetipo_id', 'labirinto_arquetipos', 'id'),
('labirinto_roteiros_gerados_fase_id_fkey', 'labirinto_roteiros_gerados', 'fase_id', 'labirinto_fases', 'id'),
('labirinto_roteiros_gerados_metafora_id_fkey', 'labirinto_roteiros_gerados', 'metafora_id', 'labirinto_metaforas', 'id'),
('labirinto_roteiros_gerados_ritual_id_fkey', 'labirinto_roteiros_gerados', 'ritual_id', 'labirinto_rituais', 'id'),
('labirinto_roteiros_gerados_session_case_id_fkey', 'labirinto_roteiros_gerados', 'session_case_id', 'session_cases', 'id'),
('labyrinth_records_client_id_fkey', 'labyrinth_records', 'client_id', 'clientes', 'id'),
('labyrinth_records_session_id_fkey', 'labyrinth_records', 'session_id', 'sessions', 'id'),
('lessons_album_book_id_fkey', 'lessons_album', 'book_id', 'books', 'id'),
('lessons_travessia_id_fkey', 'lessons', 'travessia_id', 'travessias', 'id'),
('mapa_heroina_porta_id_fkey', 'mapa_heroina', 'porta_id', 'labirinto_fases', 'id'),
('mapa_sombra_cliente_id_fkey', 'mapa_sombra', 'cliente_id', 'clientes', 'id'),
('mapa_vivo_heroina_gesto_jardim_registro_id_fkey', 'mapa_vivo_heroina', 'gesto_jardim_registro_id', 'jardim_heroina_registros', 'id'),
('mapa_vivo_heroina_session_case_id_fkey', 'mapa_vivo_heroina', 'session_case_id', 'session_cases', 'id'),
('mapa_vivo_historico_mapa_id_fkey', 'mapa_vivo_historico', 'mapa_id', 'mapa_vivo_heroina', 'id'),
('mapeamento_complexos_cliente_id_fkey', 'mapeamento_complexos', 'cliente_id', 'clientes', 'id'),
('message_logs_campaign_id_fkey', 'message_logs', 'campaign_id', 'message_campaigns', 'id'),
('message_logs_template_id_fkey', 'message_logs', 'template_id', 'message_templates', 'id'),
('mind_map_nodes_map_id_fkey', 'mind_map_nodes', 'map_id', 'mind_maps', 'id'),
('mind_map_nodes_parent_id_fkey', 'mind_map_nodes', 'parent_id', 'mind_map_nodes', 'id'),
('mind_maps_owner_id_fkey', 'mind_maps', 'owner_id', 'profiles', 'id'),
('missoes_aula_id_fkey', 'missoes', 'aula_id', 'aulas', 'id'),
('missoes_portal_id_fkey', 'missoes', 'portal_id', 'portais', 'id'),
('narrative_maps_case_id_fkey', 'narrative_maps', 'case_id', 'session_cases', 'id'),
('narrative_maps_client_id_fkey', 'narrative_maps', 'client_id', 'profiles', 'id'),
('narrative_maps_therapist_id_fkey', 'narrative_maps', 'therapist_id', 'profiles', 'id'),
('narroterapia_estudos_audio_id_fkey', 'narroterapia_estudos', 'audio_id', 'audio_assets', 'id'),
('narroterapia_reacoes_simbolicas_audio_id_fkey', 'narroterapia_reacoes_simbolicas', 'audio_id', 'audio_assets', 'id'),
('narroterapia_reacoes_simbolicas_conto_clinico_id_fkey', 'narroterapia_reacoes_simbolicas', 'conto_clinico_id', 'contos_clinicos', 'id'),
('oracle_cards_archetype_id_fkey', 'oracle_cards', 'archetype_id', 'founding_archetypes', 'id'),
('oracle_cards_deck_id_fkey', 'oracle_cards', 'deck_id', 'oracle_decks', 'id'),
('oracle_cards_district_id_fkey', 'oracle_cards', 'district_id', 'city_districts', 'id'),
('oracle_cards_tool_id_fkey', 'oracle_cards', 'tool_id', 'tools', 'id'),
('oracle_categories_oracle_id_fkey', 'oracle_categories', 'oracle_id', 'oracle_decks', 'id'),
('oracle_draws_client_id_fkey', 'oracle_draws', 'client_id', 'oracle_clients', 'id'),
('oracle_draws_oracle_id_fkey', 'oracle_draws', 'oracle_id', 'oracle_decks', 'id'),
('oracle_draws_spread_id_fkey', 'oracle_draws', 'spread_id', 'oracle_spreads', 'id'),
('oracle_spread_positions_spread_id_fkey', 'oracle_spread_positions', 'spread_id', 'oracle_spreads', 'id'),
('oracle_spreads_oracle_id_fkey', 'oracle_spreads', 'oracle_id', 'oracle_decks', 'id'),
('oracle_usage_stats_client_id_fkey', 'oracle_usage_stats', 'client_id', 'clientes', 'id'),
('oraculo_aplicacoes_pergunta_id_fkey', 'oraculo_aplicacoes', 'pergunta_id', 'oraculo_perguntas', 'id'),
('oraculo_favoritos_pergunta_id_fkey', 'oraculo_favoritos', 'pergunta_id', 'oraculo_perguntas', 'id'),
('oraculo_portal_aplicacoes_portal_id_fkey', 'oraculo_portal_aplicacoes', 'portal_id', 'oraculo_portais', 'id'),
('oraculo_portal_audios_portal_id_fkey', 'oraculo_portal_audios', 'portal_id', 'oraculo_portais', 'id'),
('oraculo_portal_essencia_portal_id_fkey', 'oraculo_portal_essencia', 'portal_id', 'oraculo_portais', 'id'),
('oraculo_portal_ferramenta_campos_ferramenta_id_fkey', 'oraculo_portal_ferramenta_campos', 'ferramenta_id', 'oraculo_portal_ferramentas', 'id'),
('oraculo_portal_ferramentas_portal_id_fkey', 'oraculo_portal_ferramentas', 'portal_id', 'oraculo_portais', 'id'),
('oraculo_portal_forja_erros_forja_id_fkey', 'oraculo_portal_forja_erros', 'forja_id', 'oraculo_portal_forjas', 'id'),
('oraculo_portal_forja_passos_forja_id_fkey', 'oraculo_portal_forja_passos', 'forja_id', 'oraculo_portal_forjas', 'id'),
('oraculo_portal_forjas_portal_id_fkey', 'oraculo_portal_forjas', 'portal_id', 'oraculo_portais', 'id'),
('oraculo_portal_jardins_portal_id_fkey', 'oraculo_portal_jardins', 'portal_id', 'oraculo_portais', 'id'),
('oraculo_portal_laboratorio_passos_laboratorio_id_fkey', 'oraculo_portal_laboratorio_passos', 'laboratorio_id', 'oraculo_portal_laboratorios', 'id'),
('oraculo_portal_laboratorios_portal_id_fkey', 'oraculo_portal_laboratorios', 'portal_id', 'oraculo_portais', 'id'),
('oraculo_portal_materiais_portal_id_fkey', 'oraculo_portal_materiais', 'portal_id', 'oraculo_portais', 'id'),
('oraculo_portal_narroterapia_perguntas_narroterapia_id_fkey', 'oraculo_portal_narroterapia_perguntas', 'narroterapia_id', 'oraculo_portal_narroterapia', 'id'),
('oraculo_portal_narroterapia_portal_id_fkey', 'oraculo_portal_narroterapia', 'portal_id', 'oraculo_portais', 'id'),
('oraculo_portal_riscos_eticos_portal_id_fkey', 'oraculo_portal_riscos_eticos', 'portal_id', 'oraculo_portais', 'id'),
('portais_jornada_id_fkey', 'portais', 'jornada_id', 'jornadas', 'id'),
('portais_modulo_id_fkey', 'portais', 'modulo_id', 'modulos_formativos', 'id'),
('portal_junguiano_modulos_config_id_fkey', 'portal_junguiano_modulos', 'config_id', 'portal_junguiano_config', 'id'),
('portal_junguiano_portais_modulo_id_fkey', 'portal_junguiano_portais', 'modulo_id', 'portal_junguiano_modulos', 'id'),
('portal_junguiano_progresso_config_id_fkey', 'portal_junguiano_progresso', 'config_id', 'portal_junguiano_config', 'id'),
('portal_junguiano_registros_portal_id_fkey', 'portal_junguiano_registros', 'portal_id', 'portal_junguiano_portais', 'id'),
('portal_progress_portal_id_fkey', 'portal_progress', 'portal_id', 'clube_portais', 'id'),
('portal_salas_sala_id_fkey', 'portal_salas', 'sala_id', 'salas', 'id'),
('post_session_closures_case_id_fkey', 'post_session_closures', 'case_id', 'session_cases', 'id'),
('post_session_closures_client_id_fkey', 'post_session_closures', 'client_id', 'profiles', 'id'),
('post_session_closures_therapist_id_fkey', 'post_session_closures', 'therapist_id', 'profiles', 'id'),
('praticas_mudra_client_id_fkey', 'praticas_mudra', 'client_id', 'clientes', 'id'),
('progresso_aluna_formacao_id_fkey', 'progresso_aluna', 'formacao_id', 'formacoes', 'id'),
('progresso_aluna_modulo_id_fkey', 'progresso_aluna', 'modulo_id', 'formacao_modulos', 'id'),
('projetos_mestria_course_id_fkey', 'projetos_mestria', 'course_id', 'courses', 'id'),
('protocolo_oracula_caminho_registro_id_fkey', 'protocolo_oracula', 'caminho_registro_id', 'jornada_heroina_registros', 'id'),
('protocolo_oracula_cliente_id_fkey', 'protocolo_oracula', 'cliente_id', 'clientes', 'id'),
('protocolo_oracula_mapa_registro_id_fkey', 'protocolo_oracula', 'mapa_registro_id', 'big5_symbolic_registros', 'id'),
('protocolo_oracula_oraculo_registro_id_fkey', 'protocolo_oracula', 'oraculo_registro_id', 'eneagrama_feminino_registros', 'id'),
('protocolo_oracula_session_case_id_fkey', 'protocolo_oracula', 'session_case_id', 'session_cases', 'id'),
('quiz_opcoes_pergunta_id_fkey', 'quiz_opcoes', 'pergunta_id', 'quiz_perguntas', 'id'),
('quiz_perguntas_quiz_id_fkey', 'quiz_perguntas', 'quiz_id', 'quizzes', 'id'),
('quiz_respostas_usuario_quiz_id_fkey', 'quiz_respostas_usuario', 'quiz_id', 'quizzes', 'id'),
('quiz_respostas_usuario_resultado_id_fkey', 'quiz_respostas_usuario', 'resultado_id', 'quiz_resultados', 'id'),
('quiz_resultados_agente_id_fkey', 'quiz_resultados', 'agente_id', 'agentes', 'id'),
('quiz_resultados_quiz_id_fkey', 'quiz_resultados', 'quiz_id', 'quizzes', 'id'),
('quizzes_portal_id_fkey', 'quizzes', 'portal_id', 'conteudo_travessias', 'id'),
('quizzes_sala_id_fkey', 'quizzes', 'sala_id', 'salas', 'id'),
('reflexoes_jornada_client_id_fkey', 'reflexoes_jornada', 'client_id', 'clientes', 'id'),
('relacionamentos_espelho_client_id_fkey', 'relacionamentos_espelho', 'client_id', 'clientes', 'id'),
('respostas_exercicios_sessao_id_fkey', 'respostas_exercicios', 'sessao_id', 'sessoes_labirinto', 'id'),
('rituais_integracao_client_id_fkey', 'rituais_integracao', 'client_id', 'clientes', 'id'),
('ritual_passages_ritual_id_fkey', 'ritual_passages', 'ritual_id', 'ritual_definitions', 'id'),
('sala_ferramentas_familia_id_fkey', 'sala_ferramentas', 'familia_id', 'travessia_familias', 'id'),
('sala_ferramentas_ferramenta_pai_id_fkey', 'sala_ferramentas', 'ferramenta_pai_id', 'sala_ferramentas', 'id'),
('sala_ferramentas_portal_id_fkey', 'sala_ferramentas', 'portal_id', 'conteudo_travessias', 'id'),
('sala_ferramentas_sala_id_fkey', 'sala_ferramentas', 'sala_id', 'salas', 'id'),
('season_books_season_id_fkey', 'season_books', 'season_id', 'oracular_seasons', 'id'),
('season_labs_season_id_fkey', 'season_labs', 'season_id', 'oracular_seasons', 'id'),
('session_archetypes_archetype_id_fkey', 'session_archetypes', 'archetype_id', 'atlas_arquetipos_femininos', 'id'),
('session_archetypes_client_id_fkey', 'session_archetypes', 'client_id', 'clientes', 'id'),
('session_archetypes_session_id_fkey', 'session_archetypes', 'session_id', 'sessions', 'id'),
('session_cases_client_id_fkey', 'session_cases', 'client_id', 'clientes', 'id'),
('session_cases_therapist_id_fkey', 'session_cases', 'therapist_id', 'profiles', 'id'),
('session_interventions_intervention_id_fkey', 'session_interventions', 'intervention_id', 'interventions', 'id'),
('session_interventions_session_id_fkey', 'session_interventions', 'session_id', 'sessions', 'id'),
('session_oracle_draws_case_id_fkey', 'session_oracle_draws', 'case_id', 'session_cases', 'id'),
('session_oracle_draws_client_id_fkey', 'session_oracle_draws', 'client_id', 'profiles', 'id'),
('session_oracle_draws_therapist_id_fkey', 'session_oracle_draws', 'therapist_id', 'profiles', 'id'),
('session_scripts_case_id_fkey', 'session_scripts', 'case_id', 'session_cases', 'id'),
('session_scripts_client_id_fkey', 'session_scripts', 'client_id', 'profiles', 'id'),
('session_scripts_narrative_map_id_fkey', 'session_scripts', 'narrative_map_id', 'narrative_maps', 'id'),
('session_scripts_therapist_id_fkey', 'session_scripts', 'therapist_id', 'profiles', 'id'),
('sessions_cidadela_card_id_fkey', 'sessions', 'cidadela_card_id', 'cidadela_oracle_cards', 'id'),
('sessions_client_id_fkey', 'sessions', 'client_id', 'clientes', 'id'),
('sessions_district_id_fkey', 'sessions', 'district_id', 'districts', 'id'),
('sessions_tool_id_fkey', 'sessions', 'tool_id', 'tools', 'id'),
('sessoes_casa_maquinas_cliente_id_fkey', 'sessoes_casa_maquinas', 'cliente_id', 'clientes', 'id'),
('sessoes_labirinto_porta_id_fkey', 'sessoes_labirinto', 'porta_id', 'labirinto_fases', 'id'),
('simulador_progresso_cenario_id_fkey', 'simulador_progresso', 'cenario_id', 'simulador_cenarios', 'id'),
('sonho_estruturado_cliente_id_fkey', 'sonho_estruturado', 'cliente_id', 'clientes', 'id'),
('sonhos_cabalisticos_client_id_fkey', 'sonhos_cabalisticos', 'client_id', 'clientes', 'id'),
('station_progress_station_id_fkey', 'station_progress', 'station_id', 'clube_estacoes', 'id'),
('studio_episodes_eixo_id_fkey', 'studio_episodes', 'eixo_id', 'studio_method_axes', 'id'),
('symbolic_template_sessions_case_id_fkey', 'symbolic_template_sessions', 'case_id', 'session_cases', 'id'),
('symbolic_template_sessions_cliente_id_fkey', 'symbolic_template_sessions', 'cliente_id', 'clientes', 'id'),
('syntheia_conversations_mode_id_fkey', 'syntheia_conversations', 'mode_id', 'syntheia_modes', 'id'),
('syntheia_conversations_voice_id_fkey', 'syntheia_conversations', 'voice_id', 'syntheia_voices', 'id'),
('syntheia_messages_conversation_id_fkey', 'syntheia_messages', 'conversation_id', 'syntheia_conversations', 'id'),
('tecela_conselho_respostas_conselho_id_fkey', 'tecela_conselho_respostas', 'conselho_id', 'tecela_conselho', 'id'),
('tecela_ressonancias_registro_id_fkey', 'tecela_ressonancias', 'registro_id', 'tecela_registros_campo', 'id'),
('tecela_supervisoes_caso_id_fkey', 'tecela_supervisoes', 'caso_id', 'tecela_casos_espelho', 'id'),
('tool_districts_district_id_fkey', 'tool_districts', 'district_id', 'city_districts', 'id'),
('tool_districts_tool_id_fkey', 'tool_districts', 'tool_id', 'tools', 'id'),
('tools_district_id_fkey', 'tools', 'district_id', 'districts', 'id'),
('tools_ferramenta_pai_id_fkey', 'tools', 'ferramenta_pai_id', 'tools', 'id'),
('tools_proximo_passo_id_fkey', 'tools', 'proximo_passo_id', 'tools', 'id'),
('torre_arquetipo_sugestao_arquetipo_id_fkey', 'torre_arquetipo_sugestao', 'arquetipo_id', 'atlas_arquetipos_femininos', 'id'),
('torre_porta_relacao_porta_id_fkey', 'torre_porta_relacao', 'porta_id', 'labirinto_portas', 'id'),
('towers_client_id_fkey', 'towers', 'client_id', 'clientes', 'id'),
('towers_session_id_fkey', 'towers', 'session_id', 'sessions', 'id'),
('travessia_comentarios_user_id_fkey', 'travessia_comentarios', 'user_id', 'profiles', 'id'),
('travessia_day_unlocks_aula_id_fkey', 'travessia_day_unlocks', 'aula_id', 'conteudo_aulas', 'id'),
('travessia_library_items_familia_id_fkey', 'travessia_library_items', 'familia_id', 'travessia_familias', 'id'),
('travessia_library_media_item_id_fkey', 'travessia_library_media', 'item_id', 'travessia_library_items', 'id'),
('travessia_library_tags_item_id_fkey', 'travessia_library_tags', 'item_id', 'travessia_library_items', 'id'),
('treinamento_respostas_caso_id_fkey', 'treinamento_respostas', 'caso_id', 'treinamento_casos_simulados', 'id'),
('upsell_opportunities_rule_id_fkey', 'upsell_opportunities', 'rule_id', 'upsell_rules', 'id'),
('user_aula_progress_aula_id_fkey', 'user_aula_progress', 'aula_id', 'conteudo_aulas', 'id'),
('user_cidadela_estado_user_id_fkey', 'user_cidadela_estado', 'user_id', 'profiles', 'id'),
('user_favorites_library_item_id_fkey', 'user_favorites', 'library_item_id', 'library_items', 'id'),
('user_progress_lesson_id_fkey', 'user_progress', 'lesson_id', 'lessons', 'id'),
('user_unlocked_rewards_reward_id_fkey', 'user_unlocked_rewards', 'reward_id', 'symbolic_rewards', 'id')
),
table_exists AS (
    SELECT table_name, true as exists 
    FROM information_schema.tables 
    WHERE table_schema = 'public'
),
column_exists AS (
    SELECT table_name, column_name, data_type, true as exists
    FROM information_schema.columns 
    WHERE table_schema = 'public'
),
constraint_exists AS (
    SELECT conname, true as exists 
    FROM pg_constraint
),
unique_cols AS (
    SELECT 
        idx.indrelid::regclass::text as table_name,
        att.attname as column_name,
        true as is_unique
    FROM pg_index idx
    JOIN pg_attribute att ON att.attrelid = idx.indrelid AND att.attnum = ANY(idx.indkey)
    WHERE idx.indisunique 
    AND array_length(idx.indkey, 1) = 1
)
SELECT 
    f.name,
    f.src_t as source_table,
    f.src_c as source_column,
    f.tgt_t as target_table,
    f.tgt_c as target_column,
    CASE 
        WHEN ce.exists THEN 'EXISTS'
        WHEN NOT te_src.exists THEN 'MISSING_SOURCE_TABLE'
        WHEN NOT co_src.exists THEN 'MISSING_SOURCE_COLUMN'
        WHEN NOT te_tgt.exists AND NOT (f.tgt_t = 'profiles' AND EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'auth')) THEN 'MISSING_TARGET_TABLE'
        WHEN NOT co_tgt.exists AND NOT (f.tgt_t = 'profiles' AND EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'auth')) THEN 'MISSING_TARGET_COLUMN'
        WHEN co_src.data_type <> co_tgt.data_type AND NOT (f.tgt_t = 'profiles') THEN 'TYPE_MISMATCH'
        WHEN NOT uc.is_unique AND NOT (f.tgt_t = 'profiles') THEN 'TARGET_NOT_UNIQUE'
        ELSE 'READY_TO_CREATE'
    END as status
FROM fks f
LEFT JOIN constraint_exists ce ON ce.conname = f.name
LEFT JOIN table_exists te_src ON te_src.table_name = f.src_t
LEFT JOIN column_exists co_src ON co_src.table_name = f.src_t AND co_src.column_name = f.src_c
LEFT JOIN table_exists te_tgt ON te_tgt.table_name = f.tgt_t
LEFT JOIN column_exists co_tgt ON co_tgt.table_name = f.tgt_t AND co_tgt.column_name = f.tgt_c
LEFT JOIN unique_cols uc ON (uc.table_name = 'public.' || f.tgt_t OR uc.table_name = f.tgt_t) AND uc.column_name = f.tgt_c;
