
-- Delete existing archetypes to avoid duplicates, then insert the 12 official ones
DELETE FROM public.atlas_arquetipos_femininos;

INSERT INTO public.atlas_arquetipos_femininos (chave, nome, territorio, descricao_clinica, manifestacoes_frequentes, perguntas_sessao, riscos_projecao, trabalhar_forca_sem_reforcar_ferida, icone, cor_acento, ordem, ativo)
VALUES
('guardia', 'A Guardiã', 'sustentacao',
 'Proteção do que é precioso. A cliente demonstra forte necessidade de preservar limites ou proteger algo importante na sua vida interior.',
 ARRAY['Necessidade de controlar o ambiente','Dificuldade em delegar','Zelo excessivo com pessoas próximas','Hipervigilância emocional'],
 ARRAY['O que em você merece ser protegido neste momento?','Que limites precisam ser honrados agora?','O que acontece quando você baixa a guarda?'],
 ARRAY['Controle excessivo ou rigidez','Confundir proteção com isolamento','Projetar fragilidade no outro para justificar o controle'],
 'Explorar limites e valores essenciais. Ajudar a cliente a distinguir proteção saudável de controle defensivo.',
 '🛡️', '#C9A24A', 1, true),

('visionaria', 'A Visionária', 'travessia',
 'Capacidade de enxergar além do visível. A cliente demonstra intuição aguçada e percepção de possibilidades futuras.',
 ARRAY['Inquietação criativa','Sensação de não pertencimento','Visões ou insights frequentes','Dificuldade com o presente concreto'],
 ARRAY['O que você consegue ver que outros ainda não veem?','Para onde sua intuição está apontando?','O que pede para ser manifestado?'],
 ARRAY['Fuga para o futuro como forma de evitar o presente','Inflação espiritual','Dificuldade de ancorar visões em ações concretas'],
 'Ajudar a ancorar visões em passos concretos. Distinguir intuição genuína de fantasia escapista.',
 '🔮', '#7B68EE', 2, true),

('curadora', 'A Curadora', 'profundidade',
 'Impulso de restaurar o que está ferido. A cliente carrega capacidade natural de acolher dor e promover regeneração.',
 ARRAY['Atração por pessoas em sofrimento','Fadiga compassiva','Dificuldade em receber cuidado','Tendência a se colocar como salvadora'],
 ARRAY['O que em você precisa de cura agora?','Quem cuida de quem cuida?','Que ferida sua está projetada no cuidado do outro?'],
 ARRAY['Síndrome do salvador','Negligenciar as próprias feridas','Usar o cuidado do outro para evitar autoconfrontação'],
 'Diferenciar cuidado genuíno de padrão codependente. Trabalhar autocuidado como prática, não como conceito.',
 '💚', '#556B57', 3, true),

('selvagem', 'A Selvagem', 'travessia',
 'Força instintiva não domesticada. A cliente sente impulsos de liberdade, autenticidade radical e ruptura com convenções.',
 ARRAY['Inquietação corporal','Rebeldia contra estruturas','Desejo de movimento e mudança','Expressão emocional intensa'],
 ARRAY['O que em você precisa ser libertado?','Que parte sua foi domesticada demais?','O que seu corpo está pedindo agora?'],
 ARRAY['Destrutividade disfarçada de liberdade','Fuga de responsabilidades','Confundir impulso com autenticidade'],
 'Canalizar a energia selvagem em expressão criativa e embodiment. Trabalhar a diferença entre impulso e instinto.',
 '🐺', '#8B4513', 4, true),

('tecela', 'A Tecelã', 'integracao',
 'Capacidade de conectar fios aparentemente desconexos. A cliente percebe padrões, tece narrativas e integra experiências.',
 ARRAY['Pensamento sistêmico natural','Capacidade de síntese','Interesse em conexões entre eventos','Tendência a buscar sentido em tudo'],
 ARRAY['Que fios da sua história pedem para ser tecidos agora?','O que conecta essas experiências aparentemente separadas?','Que padrão você percebe se repetindo?'],
 ARRAY['Intelectualização excessiva','Criar sentido onde não há','Evitar o caos necessário da transformação'],
 'Honrar a capacidade integrativa sem apressar o processo. Permitir que alguns fios permaneçam soltos.',
 '🕸️', '#9370DB', 5, true),

('exploradora', 'A Exploradora', 'travessia',
 'Impulso de ir além do conhecido. A cliente sente chamado para territórios novos, internos ou externos.',
 ARRAY['Curiosidade intensa','Dificuldade com rotina','Busca constante de novidade','Coragem para enfrentar o desconhecido'],
 ARRAY['Para onde você se sente chamada agora?','O que existe além da zona conhecida?','Que território interno ainda não foi explorado?'],
 ARRAY['Fuga geográfica ou emocional','Incapacidade de aprofundar','Confundir movimento com progresso'],
 'Ajudar a explorar profundidade, não apenas amplitude. Distinguir exploração genuína de fuga.',
 '🧭', '#2E8B57', 6, true),

('mediadora', 'A Mediadora', 'sustentacao',
 'Capacidade de criar pontes entre opostos. A cliente naturalmente busca equilíbrio e harmonia relacional.',
 ARRAY['Tendência a evitar conflitos','Sensibilidade às necessidades dos outros','Capacidade diplomática','Dificuldade em se posicionar'],
 ARRAY['O que acontece quando você para de mediar?','Que conflito interno está pedindo atenção?','O que você realmente pensa, sem filtrar para os outros?'],
 ARRAY['Perda de identidade na mediação','Codependência disfarçada de diplomacia','Evitação de conflito necessário'],
 'Fortalecer a voz própria. Trabalhar a diferença entre paz genuína e evitação de conflito.',
 '⚖️', '#4682B4', 7, true),

('estrategista', 'A Estrategista', 'sustentacao',
 'Inteligência tática e capacidade de planejamento. A cliente pensa em termos de objetivos, recursos e caminhos.',
 ARRAY['Pensamento analítico forte','Dificuldade com improviso','Necessidade de controle sobre resultados','Eficiência como valor central'],
 ARRAY['Que plano seu precisa ser abandonado agora?','O que acontece quando as coisas fogem do seu controle?','Existe algo que não pode ser resolvido com estratégia?'],
 ARRAY['Racionalização de emoções','Frieza como defesa','Manipulação disfarçada de estratégia'],
 'Integrar inteligência emocional à inteligência estratégica. Trabalhar rendição e improviso como competências.',
 '♟️', '#708090', 8, true),

('sensitiva', 'A Sensitiva', 'profundidade',
 'Percepção sutil e porosa. A cliente absorve atmosferas, emoções alheias e nuances invisíveis para outros.',
 ARRAY['Alta sensibilidade sensorial','Fadiga em ambientes intensos','Percepção de atmosferas emocionais','Dificuldade com limites energéticos'],
 ARRAY['O que você está sentindo que não é seu?','Como seu corpo reage a este tema?','Que limites energéticos precisam ser criados?'],
 ARRAY['Confundir empatia com fusão','Usar sensibilidade como identidade','Vitimização pela própria porosidade'],
 'Desenvolver filtros e limites saudáveis. Transformar sensibilidade em ferramenta clínica, não em vulnerabilidade.',
 '🌙', '#DDA0DD', 9, true),

('criadora', 'A Criadora', 'integracao',
 'Impulso de dar forma ao que não existia. A cliente sente necessidade de expressar, construir e manifestar.',
 ARRAY['Expressão artística ou criativa','Inquietação quando não pode criar','Ideias abundantes','Dificuldade em finalizar projetos'],
 ARRAY['O que precisa nascer através de você agora?','Que criação está sendo gestada?','O que bloqueia sua expressão?'],
 ARRAY['Perfeccionismo criativo','Usar criação para evitar confrontação','Identificação excessiva com a obra'],
 'Apoiar o processo criativo sem apressar o nascimento. Trabalhar a diferença entre criação autêntica e performance.',
 '🎨', '#FF6347', 10, true),

('sobrevivente', 'A Sobrevivente', 'profundidade',
 'Resiliência forjada na adversidade. A cliente carrega força que nasceu da travessia de situações difíceis.',
 ARRAY['Hipervigilância','Desconfiança como padrão','Força em situações de crise','Dificuldade em receber ajuda'],
 ARRAY['O que essa parte sobrevivente tentou proteger em você?','É seguro descansar agora?','Que permissão você precisa dar a si mesma?'],
 ARRAY['Glorificar o sofrimento','Identidade construída apenas sobre a dor','Incapacidade de viver fora do modo de sobrevivência'],
 'Honrar a força da sobrevivência sem fixar a identidade nela. Ajudar na transição de sobreviver para viver.',
 '🔥', '#B22222', 11, true),

('mestra', 'A Mestra', 'integracao',
 'Sabedoria integrada que deseja ser transmitida. A cliente sente chamado para ensinar, guiar ou sustentar processos.',
 ARRAY['Desejo de transmitir conhecimento','Responsabilidade com o saber','Tendência a ser procurada como referência','Solidão da autoridade'],
 ARRAY['O que você sabe que precisa ser compartilhado?','Que sabedoria nasceu das suas travessias?','O que ainda precisa ser aprendido antes de ensinar?'],
 ARRAY['Inflação pelo papel de mestra','Ensinar para evitar aprender','Usar autoridade como defesa contra vulnerabilidade'],
 'Integrar humildade à maestria. Manter a posição de eterna aprendiz mesmo no papel de guia.',
 '👑', '#DAA520', 12, true);
